# Generated by Django 5.2.17 on 2026-08-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
